packages:
  - ./analytics_reports
  - ./antivirus_definitions_downloader
  - ./antivirus_scanner
  - ./assigned_participants
  - ./broadcast_migration
  - ./broadcast_notifier_kinesis_consumer
  - ./cmnote_migration
  - ./cognito_admin
  - ./cognito_custom_message_trigger
  - ./cognito_jwt_keys_downloader
  - ./cognito_post_auth_trigger
  - ./cognito_pre_auth_trigger
  - ./cognito_presignup_trigger
  - ./cognito_resend_confirmation
  - ./cognito_signup
  - ./cognito_user_migration_trigger
  - ./cognito_user_verification_status
  - ./custom_authorizer
  - ./email_notifier_kinesis_consumer
  - ./email_pruner
  - ./facial_recognition
  - ./graphql
  - ./kinesis_consumer
  - ./kinesis_failed_events_handler
  - ./kinesis_producer_create_cognito_user
  - ./kms_helper
  - ./lambda_warmer
  - ./log_to_lambda
  - ./message_sentiment_analysis
  - ./monitor_expiring_shares
  - ./mypokket_reports
  - ./mysql-binlog-kinesis-producer
  - ./notification_notifier
  - ./plan-template-generator
  - ./plan_item_recurrences_migration
  - ./pokket_search
  - ./pokket_user
  - ./post_auth_logger
  - ./pre_auth_logger
  - ./provider_search
  - ./rds_to_dynamodb
  - ./rds_to_dynamodb_sync
  - ./reassign_case_kinesis_consumer
  - ./s3_listener
  - ./server_utilities
  - ./signed_url
  - ./sms_enabled_participants
  - ./sms_listener
  - ./sns_listener
  - ./sp_onboarding_listener
  - ./task_counts_calculator
  - ./task_counts_kinesis_consumer
  - ./unassign_participant_service
  - ./unread_notif_counts_kinesis_consumer
  - ./update_temp_flag
  - ./username_exists
  - ./websocket_connect_handler
  - ./websocket_disconnect_handler
  - ./websocket_on_message_handler
